services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: son-en-breugel-frontend
    ports:
      - "3000:80"
    networks:
      - son-en-breugel-network
    restart: unless-stopped

networks:
  son-en-breugel-network:
    external: true